#+startup: showall
#+TITLE: Deptree: ASDF system dependency listing and archiving
#+PROPERTY: header-args :results output
#+OPTIONS: toc:nil
#+INFOJS_OPT: view:showall toc:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper, 11pt]
#+LaTeX_HEADER: \usepackage{minted}
#+LaTeX_HEADER: \usemintedstyle{common-lisp, fontsize=\scriptsize}
#+LaTeX_HEADER: \usepackage[left=0.6in, right=0.6in]{geometry}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \pagestyle{fancyplain}
#+LATEX_HEADER: \lhead{}
#+LATEX_HEADER: \rhead{}
#+LATEX_HEADER: \lfoot{}
#+LATEX_HEADER: \rfoot{}
#+HTML_HEAD: <link rel="stylesheet" href="https://sandyuraz.com/styles/org.min.css">

* Enumerating system's dependencies

(deptree /system-name/)

Example: ~(deptree "hunchentoot")~

The resulting list of system names is deduplicated and pruned of dependencies within same system directories.

* Listing dependencies' pathnames

(systems-paths /dependencies/)

Example: ~(systems-paths (deptree "hunchentoot"))~

* Archiving system's dependencies

(systems-archive /dependencies/ /tarball-pathname/ &key (/sanitize-p t/))

Example: ~(systems-archive (deptree "hunchentoot") #p"/tmp/hunchentoot-deps.tgz")~

All systems directores are stored flat regarless their original absolute pathnames. As feature-conditional
dependencies are honored, please ensure you're archiving from the relevant platform.

If :sanitize-p is NIL, the function will not clean up git and Mercurial DVCS data from the archives.
